services:
  mysql:
    image: mysql:8.0
    container_name: conciertos_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: conciertos_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: conciertos_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_DSN: "root:12345@tcp(mysql:3306)/conciertos_db?charset=utf8mb4&parseTime=True&loc=Local"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: conciertos_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data: